site_name: Paintomics Documentation
pages:
   - Home: 'index.md'
   - 'Getting started':
      - 'Step-by-step guide': '8_step_by_step.md'
      - 'Accepted input data': '2_1_accepted_input.md'
      - 'Cloud Drive': '2_2_cloud_drive.md'
      - 'Pathway Enrichment Analysis (PEA)': '4_1_pathway_enrichment.md'
      - 'Hierarchical classifications for pathways': '4_2_kegg_categories.md'
      - 'The pathways interaction network': '4_3_pathways_network.md'
      - 'Metabolite hub analysis': '4_4_metabolite_hub_analysis.md'
      - 'Metabolite class activity analysis': '4_5_metabolite_class_activity_analysis.md'
      - 'Regulatory omics analysis': '4_6_Regulatory_omics.md'
      - 'Metagenes': '4_7_Metagenes.md'
      - 'Multi-omic pathway-based visualisation': '5_1_browsing_pathways.md'
   - FAQ:
      - 'Frequently asked questions': '9_faq.md'
   - 'Additional information':
      - 'The KEGG pathways database': '1_1_kegg.md'
      - 'The Reactome pathways database': '1_2_reactome.md'
      - 'The MapMan pathways database': '1_3_mapman.md'
      - 'The supported ID and database': '1_4_id.md'
      - 'The update history': '1_5_update_history.md'
   - Install:
      - 'Installing PaintOmics 4': '0_install.md'
   - About:
      - 'License': '7_license.md'
theme: readthedocs
