site_name: Paintomics v3.0 Documentation
pages:
- ['index.md', 'Home']
- ['8_step_by_step.md', 'Getting started', 'Step-by-step guide']

- ['2_1_accepted_input.md', 'Getting started', 'Accepted input data']
- ['2_2_cloud_drive.md', 'Getting started', 'Cloud Drive']
- ['4_1_pathway_enrichment.md', 'Getting started', 'Pathway Enrichment Analysis (PEA)']
- ['4_2_kegg_categories.md', 'Getting started', 'Hierarchical classifications for pathways']
- ['4_3_pathways_network.md', 'Getting started', 'The pathways interaction network']
- ['5_1_browsing_pathways.md', 'Getting started', 'Multi-omic pathway-based visualisation']
- ['9_faq.md', 'FAQ', 'Frequently asked questions']

- ['1_kegg.md', 'Additional information', 'The KEGG Pathways database']

- ['0_install.md', 'Install', 'Installing PaintOmics 3']
- ['7_license.md', 'About', 'License']
theme: readthedocs
