#!/usr/bin/env bash
#
# End-to-end regression over every example dataset in
# PaintomicsServer/src/examplefiles/datasets/.
#
# Each dataset is run through the real pipeline in a fresh interpreter
# (src/benchmarks/bench_runner.py: the same job methods the servlets call, in
# the same order, for all four pipelines), the result is normalised
# (scripts/regression.py: job IDs, timestamps, absolute paths and UUIDs
# stripped; set-derived collections sorted) and compared bit for bit with the
# stored baseline under tests/baseline/<dataset>/.
#
# Output: one "PASS <dataset>" / "FAIL <dataset> (<why>)" line per dataset
# and a final "N/N passed". Exit status 0 only when every dataset passed.
# Nothing time-dependent is printed, so two runs of the same tree print the
# same text.
#
# Usage:
#   scripts/regression.sh                    # every dataset, compare
#   scripts/regression.sh 01-gene-single-condition 05-regulatory-mirna
#   scripts/regression.sh --write-baseline   # create MISSING baselines only
#
# --write-baseline never overwrites: a dataset that already has a baseline is
# compared, not rewritten. tests/baseline/ is regenerated by deleting it on
# purpose, never by this script.
#
# Environment:
#   PYTHON                  interpreter with the server's requirements
#                           (default: python3)
#   PAINTOMICS_KEGG_DATA    KEGG_DATA directory (required)
#   PAINTOMICS_CLIENT_TMP   scratch directory for job files
#                           (default: a fresh temporary directory)
#   MONGODB_HOST/PORT       where the species databases live (serverconf
#                           defaults: localhost:27017)
#   REGRESSION_WORK         where per-dataset outputs and logs are kept
#                           (default: a fresh temporary directory, printed to
#                           stderr)
#   REGRESSION_TIMEOUT      per-dataset kill timeout in seconds (default 3600)
#
# Requirements on the host: MongoDB with the species the datasets use
# (all are mmu), Rscript with the packages the metagene and hub scripts
# load, the more-rs binary at src/common/bioscripts/more-rs (or named by
# PAINTOMICS_MORE_RS) for the MORE datasets, and
# examplefiles/GTF/sorted_mmu.gtf for the region datasets
# (deploy/fetch-example-gtf.sh builds it).

set -u
set -o pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVER="$ROOT/PaintomicsServer"
PYTHON="${PYTHON:-python3}"
REGRESSION_TIMEOUT="${REGRESSION_TIMEOUT:-3600}"
HELPER="$ROOT/scripts/regression.py"

WRITE_BASELINE=0
DATASETS=()
for arg in "$@"; do
    case "$arg" in
        --write-baseline) WRITE_BASELINE=1 ;;
        -h|--help) sed -n '2,45p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        --*) echo "regression: unknown option $arg" >&2; exit 64 ;;
        *) DATASETS+=("$arg") ;;
    esac
done

if [ -z "${PAINTOMICS_KEGG_DATA:-}" ]; then
    echo "regression: PAINTOMICS_KEGG_DATA must point at the KEGG_DATA directory" >&2
    exit 64
fi
export PAINTOMICS_KEGG_DATA

if [ -z "${PAINTOMICS_CLIENT_TMP:-}" ]; then
    PAINTOMICS_CLIENT_TMP="$(mktemp -d "${TMPDIR:-/tmp}/paintomics-regression-tmp.XXXXXX")"
fi
export PAINTOMICS_CLIENT_TMP
mkdir -p "$PAINTOMICS_CLIENT_TMP"

if [ -z "${REGRESSION_WORK:-}" ]; then
    REGRESSION_WORK="$(mktemp -d "${TMPDIR:-/tmp}/paintomics-regression.XXXXXX")"
    echo "regression: outputs under $REGRESSION_WORK" >&2
fi
mkdir -p "$REGRESSION_WORK"

# A missing server config is the usual fresh-checkout failure; the template
# reads every setting from the environment, so it is the right file to use.
if [ ! -f "$SERVER/src/conf/serverconf.py" ]; then
    cp "$SERVER/src/resources/example_serverconf.py" "$SERVER/src/conf/serverconf.py"
    echo "regression: bootstrapped src/conf/serverconf.py from the template" >&2
fi
mkdir -p "$SERVER/src/log"

if [ ! -s "$SERVER/src/examplefiles/GTF/sorted_mmu.gtf" ]; then
    echo "regression: examplefiles/GTF/sorted_mmu.gtf is missing; the region datasets need it (deploy/fetch-example-gtf.sh)" >&2
    exit 66
fi

# The MORE datasets are PLS1 jobs, which the server runs on the Rust port
# (more-rs) whenever it can find one -- as the development and production
# hosts do. The baseline holds the port's output; R's MORE writes the same
# numbers but orders one table differently, so a host without the port would
# fail the MORE datasets for a reason that has nothing to do with the code
# under test. Refuse early instead of reporting that as a regression.
if [ -z "${PAINTOMICS_MORE_RS:-}" ] && [ ! -x "$SERVER/src/common/bioscripts/more-rs" ]; then
    echo "regression: no more-rs binary at src/common/bioscripts/more-rs and PAINTOMICS_MORE_RS is unset; the MORE datasets need the Rust port (build it from github.com/TianYuan-Liu/MORE, rust/)" >&2
    exit 66
fi

# Every dataset, in manifest order, unless the caller named some.
ALL=()
while read -r dataset scenario pipeline; do
    ALL+=("$dataset")
done < <("$PYTHON" "$HELPER" list)
if [ ${#ALL[@]} -eq 0 ]; then
    echo "regression: no datasets in the manifest" >&2
    exit 65
fi
if [ ${#DATASETS[@]} -eq 0 ]; then
    DATASETS=("${ALL[@]}")
fi

passed=0
total=0
for dataset in "${DATASETS[@]}"; do
    total=$((total + 1))
    work="$REGRESSION_WORK/$dataset"
    rm -rf "$work"
    mkdir -p "$work"

    if ! "$PYTHON" "$HELPER" run "$dataset" --work "$work" --python "$PYTHON" \
            --timeout "$REGRESSION_TIMEOUT" --checkout "$ROOT" \
            --client-tmp "$PAINTOMICS_CLIENT_TMP" --kegg-data "$PAINTOMICS_KEGG_DATA"; then
        echo "FAIL $dataset (pipeline error; see $work/bench.log)"
        tail -n 15 "$work/bench.log" 2>/dev/null | sed 's/^/    /'
        continue
    fi

    if [ ! -d "$ROOT/tests/baseline/$dataset" ]; then
        if [ "$WRITE_BASELINE" -eq 1 ]; then
            if "$PYTHON" "$HELPER" write "$dataset" --work "$work"; then
                echo "PASS $dataset (baseline written)"
                passed=$((passed + 1))
            else
                echo "FAIL $dataset (could not write baseline)"
            fi
        else
            echo "FAIL $dataset (no baseline under tests/baseline/$dataset)"
        fi
        continue
    fi

    if "$PYTHON" "$HELPER" compare "$dataset" --work "$work" > "$work/compare.txt"; then
        echo "PASS $dataset"
        passed=$((passed + 1))
    else
        echo "FAIL $dataset (differs from tests/baseline/$dataset)"
        sed 's/^/    /' "$work/compare.txt"
    fi
done

echo "$passed/$total passed"
[ "$passed" -eq "$total" ]
