"""Run a figure bundle's `figure.py` in a subprocess that cannot run away.

Why this file exists. `figure_templates.py` writes a bundle -- `data.tsv` plus
a self-contained `figure.py` -- and something has to execute that script to get
`figure.svg/pdf/png`. Executing it *in the server process* is not an option:
this deployment runs `processes=1 threads=4` (four uWSGI threads serve the whole
site), so a plotting call that allocates a few GB, spins forever, or raises at
import time would not damage one report -- it would be an outage. Every guard
below exists to keep a bad figure a *bad figure* rather than a dead server.

What is actually contained, and what is not. Be exact about this, because a
sandbox that is believed to do more than it does is worse than none:

  * **Wall clock** -- a hard `timeout` (default 90 s) kills the child. Contains
    an infinite loop that never burns CPU (e.g. `time.sleep`), which RLIMIT_CPU
    would never catch.
  * **CPU** -- `RLIMIT_CPU` (60 s). Contains a genuine spin that the wall clock
    would only catch 30 s later, and does it via SIGXCPU rather than our kill.
  * **Address space** -- `RLIMIT_AS` (1 GB). Contains the classic
    `np.zeros((n, n))` typo that would otherwise take the box's memory with it.
  * **File size** -- `RLIMIT_FSIZE` (50 MB). Contains a runaway write. This is
    also the only ceiling on a write the script makes *outside* the bundle.
  * **Environment** -- the child gets four variables and nothing else. No
    `HOME` (so it cannot read or write the service account's dotfiles by
    accident), no API keys, no `PYTHONPATH`. `-I` isolates the interpreter from
    user site-packages and from `PYTHON*` environment variables as well.

  * **NOT contained: the filesystem.** There is no kernel-level jail here.
    seccomp/unshare need root, which we do not have on Garnatxa or on UV, so a
    script that opens an absolute path outside the bundle *will* write there.
    What we have instead is: `cwd=bundle_dir`, so every RELATIVE path the script
    uses lands inside the bundle; `RLIMIT_FSIZE`, so nothing it writes anywhere
    can be large; and the fact that `figure.py` is generated by our own
    templates and never by the model (design §3, approach A). `files_written`
    reports only what appeared inside the bundle -- a stray absolute write is
    invisible to this function, and saying so here is the point.
  * **NOT contained: the network.** Same reason -- no root, no netns. Nothing
    in a generated `figure.py` opens a socket, and the matplotlib font cache is
    warmed at server start so even the font machinery has no reason to. The
    design says to document this rather than pretend, so it is documented.

Platform guard. `resource` is POSIX-only; on a platform without it we degrade
to *no* `preexec_fn` at all and only the wall-clock timeout applies. Even on
POSIX the three limits are applied independently and best-effort, because they
are not uniformly supported: **macOS refuses `RLIMIT_AS` outright** (setrlimit
raises `ValueError: current limit exceeds maximum limit` even for a lower
value, verified on Darwin with both soft and hard at RLIM_INFINITY). If one
limit were allowed to abort the whole `preexec_fn`, the child would die with
`SubprocessError` and every render on a developer's Mac would fail for a reason
that has nothing to do with the figure. So each limit is set in its own
try/except and the ones the kernel refuses are simply absent -- named in
`render.log`, not swallowed in silence.

Threading note. `preexec_fn` runs in the forked child of a MULTITHREADED
process, where anything that takes a lock can deadlock forever -- the child
holds a snapshot of mutexes that no longer have owners. The function below
therefore does nothing but `setrlimit`: no logging, no imports, no allocation
beyond the tuples already built in the parent. Do not add an f-string to it.
"""
from __future__ import annotations

import logging
import os
import subprocess
import sys
from dataclasses import dataclass, field
from typing import List

logger = logging.getLogger(__name__)

try:                                    # POSIX only; absent on Windows.
    import resource                     # used by _limit_plan / _make_preexec
    _HAVE_RESOURCE = True
except ImportError:                     # pragma: no cover -- not our deployment
    resource = None
    _HAVE_RESOURCE = False

# The script the bundle is required to carry, and the log we leave beside it.
SCRIPT_NAME = "figure.py"
RENDER_LOG = "render.log"

# matplotlib writes a font cache on first use. Point it INSIDE the bundle so a
# render never touches a shared cache directory (two jobs rendering at once used
# to be able to corrupt each other's cache) and never needs $HOME.
MPLCONFIG_DIRNAME = ".mplconfig"

# Ceilings. Module-level so a test can lower one and exercise the real code path
# without writing 50 MB to prove a guard works.
RLIMIT_AS_BYTES = 1 * 1024 * 1024 * 1024          # 1 GB of address space
RLIMIT_CPU_SECONDS = 60                           # design §4.3
RLIMIT_FSIZE_BYTES = 50 * 1024 * 1024             # 50 MB per file

DEFAULT_TIMEOUT = 90                              # wall clock, design §4.3
STDERR_TAIL_CHARS = 2000                          # what the agent gets to read


@dataclass
class RenderResult:
    """The outcome of one render. A FAILED RENDER IS DATA, never an exception.

    The tool that calls this turns a failure into a GAP line and a `fails:
    render` verdict (design §5); it cannot do that if the failure arrives as a
    traceback out of a subprocess call. Every path below returns one of these.

    returncode is the child's exit status: 0 on success, negative for a signal
    (-9 after we kill a timed-out child, -25/SIGXFSZ when RLIMIT_FSIZE fires,
    -24/SIGXCPU when RLIMIT_CPU fires), and -1 when we never got as far as
    starting a child (no bundle, no script, exec failed).
    """
    ok: bool
    returncode: int
    seconds: float
    stderr_tail: str
    files_written: List[str] = field(default_factory=list)


def _limit_plan():
    """[(resource constant, limit value, human name)] to attempt in the child.

    Built in the PARENT so the child's pre-exec code does no attribute lookups
    on a module dict it may not be safe to touch after a fork.
    """
    if not _HAVE_RESOURCE:
        return []
    plan = []
    for attr, value in (("RLIMIT_AS", RLIMIT_AS_BYTES),
                        ("RLIMIT_CPU", RLIMIT_CPU_SECONDS),
                        ("RLIMIT_FSIZE", RLIMIT_FSIZE_BYTES)):
        const = getattr(resource, attr, None)
        if const is not None:
            plan.append((const, int(value), attr))
    return plan


def _make_preexec(plan):
    """A `preexec_fn` that applies each limit best-effort, or None.

    Returning None (rather than a no-op function) matters: `preexec_fn` is
    unsupported on some platforms and forces the slow fork path everywhere
    else, so we ask for it only when there is something to set.
    """
    if not plan:
        return None
    setrlimit = resource.setrlimit          # bound before the fork, on purpose

    def _apply():
        # No logging, no imports, no formatting -- see the threading note above.
        for const, value, _name in plan:
            try:
                setrlimit(const, (value, value))
            except (ValueError, OSError):
                # This kernel refuses this limit (macOS + RLIMIT_AS). Continue:
                # losing one ceiling is survivable, losing the whole child to a
                # SubprocessError from preexec_fn is not.
                pass

    return _apply


def _child_env(bundle_dir):
    """The four variables the child is allowed to see.

    Deliberately not inherited: HOME, PYTHONPATH, every API key this process
    holds. A generated plotting script has no business reading any of them, and
    a subprocess that inherits `os.environ` is the standard way a secret ends up
    in a log file the user can download.
    """
    return {
        "MPLBACKEND": "Agg",                        # never try to open a display
        "MPLCONFIGDIR": os.path.join(bundle_dir, MPLCONFIG_DIRNAME),
        # PATH is needed for the interpreter's own subprocess machinery and for
        # any external converter matplotlib shells out to; LANG keeps text
        # rendering (and float formatting) from depending on the service
        # account's locale, which is how a "." became a "," in a data.tsv once.
        "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
        "LANG": os.environ.get("LANG", "C.UTF-8"),
    }


def _snapshot(bundle_dir):
    """{relative path: (size, mtime_ns)} for everything in the bundle.

    Used before and after so `files_written` names what this render produced
    rather than what happened to be lying in the directory. The mpl cache and
    our own log are excluded -- they are ours, not the script's output.
    """
    seen = {}
    skip_top = {MPLCONFIG_DIRNAME}
    for root, dirs, files in os.walk(bundle_dir):
        if root == bundle_dir:
            dirs[:] = [d for d in dirs if d not in skip_top]
        for name in files:
            full = os.path.join(root, name)
            rel = os.path.relpath(full, bundle_dir)
            if rel == RENDER_LOG:
                continue
            try:
                st = os.stat(full)
            except OSError:
                continue
            seen[rel] = (st.st_size, st.st_mtime_ns)
    return seen


def _write_log(bundle_dir, header, stdout, stderr):
    """Persist the child's output beside the bundle; never let this raise.

    The log is the only forensics a failed render leaves, and the design keeps
    the bundle even when the render fails, so a log write that blew up would
    destroy exactly the evidence it exists to preserve.
    """
    path = os.path.join(bundle_dir, RENDER_LOG)
    try:
        with open(path, "w", encoding="utf-8", errors="replace") as fh:
            fh.write(header)
            fh.write("\n--- stdout ---\n")
            fh.write(stdout or "")
            fh.write("\n--- stderr ---\n")
            fh.write(stderr or "")
            fh.write("\n")
    except OSError:
        logger.warning("figure_sandbox: could not write %s", path)


def render(bundle_dir, timeout=DEFAULT_TIMEOUT):
    """Execute `<bundle_dir>/figure.py` under the ceilings above.

    Returns a RenderResult. Never raises -- see RenderResult's docstring.

    `[sys.executable, "-I", "figure.py"]`: `-I` is isolated mode (implies -E and
    -s, and on 3.11+ -P), so the child ignores PYTHON* variables, user
    site-packages, and the script directory as an import root. A generated
    `figure.py` imports only matplotlib, numpy and csv, so it loses nothing;
    what it gains is that a stray `sitecustomize.py` on a developer's box cannot
    change what a rendered figure looks like.
    """
    started = _now()
    bundle_dir = os.path.abspath(bundle_dir)

    if not os.path.isdir(bundle_dir):
        # Not an exception: the caller wants a verdict, and "there is no bundle"
        # is one. Raising here would take down a run for a mkdir that failed.
        return RenderResult(False, -1, 0.0,
                            "figure_sandbox: no such bundle directory: %s"
                            % bundle_dir)

    script = os.path.join(bundle_dir, SCRIPT_NAME)
    if not os.path.isfile(script):
        msg = ("figure_sandbox: bundle has no %s -- nothing to render"
               % SCRIPT_NAME)
        _write_log(bundle_dir, msg, "", "")
        return RenderResult(False, -1, 0.0, msg)

    # matplotlib refuses to start if MPLCONFIGDIR does not exist and cannot be
    # created; make it here so the failure is ours and legible, not a warning
    # buried in the child's stderr.
    try:
        os.makedirs(os.path.join(bundle_dir, MPLCONFIG_DIRNAME), exist_ok=True)
    except OSError:
        pass

    plan = _limit_plan()
    attempted = ", ".join(name for _c, _v, name in plan) or "none"
    header = ("figure_sandbox: %s -I %s\n"
              "  cwd            : %s\n"
              "  wall timeout   : %ss\n"
              "  rlimits tried  : %s\n"
              "  (a limit this kernel refuses is skipped -- macOS refuses "
              "RLIMIT_AS)\n"
              % (sys.executable, SCRIPT_NAME, bundle_dir, timeout, attempted))

    before = _snapshot(bundle_dir)
    timed_out = False
    stdout = stderr = ""

    try:
        proc = subprocess.run(
            [sys.executable, "-I", SCRIPT_NAME],
            cwd=bundle_dir,
            env=_child_env(bundle_dir),
            stdin=subprocess.DEVNULL,       # a script that waits on stdin would
                                            # otherwise hang until the timeout
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout,
            preexec_fn=_make_preexec(plan),
        )
        returncode = proc.returncode
        stdout, stderr = proc.stdout or "", proc.stderr or ""
    except subprocess.TimeoutExpired as exc:
        # run() has already killed the child for us; the partial output it
        # captured is on the exception and is usually the most useful part.
        timed_out = True
        returncode = -9
        stdout = _as_text(exc.stdout)
        stderr = _as_text(exc.stderr)
        stderr = ("[figure_sandbox] TIMEOUT: killed after %ss of wall clock\n%s"
                  % (timeout, stderr))
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        # Exec failed, or preexec_fn blew up on a platform we mis-read. Still a
        # verdict, still not an exception for the caller.
        returncode = -1
        stderr = "[figure_sandbox] could not start the render: %r" % (exc,)

    seconds = round(_now() - started, 3)
    _write_log(bundle_dir, header, stdout, stderr)

    after = _snapshot(bundle_dir)
    files_written = sorted(rel for rel, meta in after.items()
                           if before.get(rel) != meta)

    ok = (returncode == 0) and not timed_out
    return RenderResult(ok=ok, returncode=returncode, seconds=seconds,
                        stderr_tail=stderr[-STDERR_TAIL_CHARS:],
                        files_written=files_written)


def _as_text(blob):
    """TimeoutExpired carries bytes when text=True was not honoured."""
    if blob is None:
        return ""
    if isinstance(blob, bytes):
        return blob.decode("utf-8", "replace")
    return blob


def _now():
    # monotonic, not time.time: a render's duration must not change because
    # ntpd stepped the clock mid-run.
    import time
    return time.monotonic()
