#!/usr/bin/env python3
"""Behaviour of src/common/ExampleBundle.py: the "Download example data" archive.

The property under test is the one the old static zip broke. That file was
built in 2017, held twelve files from a dataset the picker no longer offers, and
was regenerated by nothing -- so "Load example" and "Download example data"
handed out different experiments, and there was no test that could have noticed
because neither side knew about the other.

So the central assertion here is an equality between the two: every file that a
scenario in the picker would run on is a file in the archive. It runs against
the **real** bundled catalogue, because a synthetic manifest cannot catch the
failure that actually happened (a real dataset drifting away from a real zip).
The synthetic cases below it cover the edges -- an oversized member, an unknown
id, a file two scenarios share -- which the real tree does not always exhibit.

Usage:
    cd PaintomicsServer
    python -m src.tests.test_example_bundle
"""
import json
import os
import shutil
import sys
import tempfile
import unittest
import zipfile

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from src.common import ExampleBundle
from src.common import ExampleDatasets


REAL_EXAMPLE_FILES = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "examplefiles"))

PREFIX = ExampleBundle.BUNDLE_STEM + "/"
DOCUMENT = PREFIX + ExampleBundle.DOCUMENT_NAME


def buildInto(directory, exampleFilesDir=REAL_EXAMPLE_FILES, scenarioId=None):
    """Build an archive at a path we control and return the open ZipFile."""
    path = os.path.join(directory, "bundle.zip")
    ExampleBundle.buildBundle(exampleFilesDir, path, scenarioId)
    return zipfile.ZipFile(path)


class RealCatalogueBundleTest(unittest.TestCase):
    """Against the datasets this checkout actually ships."""

    @classmethod
    def setUpClass(cls):
        ExampleDatasets.clearCache()
        cls.directory = tempfile.mkdtemp(prefix="paintomics-bundle-test-")
        cls.archive = buildInto(cls.directory)
        cls.names = set(cls.archive.namelist())
        cls.document = cls.archive.read(DOCUMENT).decode("utf-8")
        cls.scenarios = ExampleDatasets.listScenarios(REAL_EXAMPLE_FILES)

    @classmethod
    def tearDownClass(cls):
        cls.archive.close()
        shutil.rmtree(cls.directory, ignore_errors=True)

    def test_every_file_the_picker_would_run_on_is_in_the_archive(self):
        """The equality the static zip broke: downloadable == loadable.

        With one stated exception: a member over MAX_MEMBER_BYTES is skipped
        by design (the deploy-fetched mouse GTF -- half a gigabyte a download
        click must not incur) and the contract for it is to be *named in the
        document* instead. Asserting bare membership here made the test fail
        on exactly the machines that have the GTF, which is every deployment.
        """
        self.assertTrue(self.scenarios, "no scenarios available to test")
        for scenario in self.scenarios:
            for relative in ExampleDatasets.declaredFiles(scenario):
                absolute = ExampleDatasets.absolutePath(REAL_EXAMPLE_FILES, relative)
                if not os.path.isfile(absolute):
                    continue                    # listScenarios would have dropped it
                if os.path.getsize(absolute) > ExampleBundle.MAX_MEMBER_BYTES:
                    self.assertIn(relative, self.document,
                                  "'%s' runs on %s, which is too large to "
                                  "bundle, so the document must say so"
                                  % (scenario.get("id"), relative))
                    continue
                self.assertIn(PREFIX + relative, self.names,
                              "'%s' runs on %s but it is not in the archive"
                              % (scenario.get("id"), relative))

    def test_every_scenario_contributes_its_readme_and_expectations(self):
        """The archive has to explain itself offline, not just carry data."""
        for scenario in self.scenarios:
            folders = ExampleBundle._scenarioFolders(scenario)
            self.assertTrue(folders, "%s declares no dataset folder"
                            % scenario.get("id"))
            self.assertIn(PREFIX + folders[0] + "/README.md", self.names)

    def test_the_manifest_travels_with_the_data(self):
        manifestName = ExampleDatasets.MANIFEST_NAME.replace(os.sep, "/")
        self.assertIn(PREFIX + manifestName, self.names)

    def test_a_shared_file_is_stored_once(self):
        """stategra-mirna reads 08's matrix; two copies would be two truths."""
        stored = self.archive.namelist()
        self.assertEqual(len(stored), len(set(stored)))

    def test_nothing_escapes_the_archive_root(self):
        """A member outside the prefix is a zip-slip waiting for a bad unzipper."""
        for name in self.names:
            self.assertTrue(name.startswith(PREFIX), "%s escapes the root" % name)
            self.assertNotIn("..", name.split("/"))

    def test_the_document_states_simulated_or_real_for_every_dataset(self):
        """The question every README answered in one word and never explained."""
        for scenario in self.scenarios:
            self.assertIn(scenario.get("id"), self.document,
                          "the provenance document never mentions %s"
                          % scenario.get("id"))
        self.assertIn("simulated", self.document)
        self.assertIn("real measurements", self.document)

    def test_the_document_quotes_the_generators_real_constants(self):
        """Prose that drifts from the generator is confidently wrong.

        The numbers are read out of `simulate` at render time, so this asserts
        the wiring rather than the values: change an effect size and the
        document changes with it, and if the import silently broke, the
        rendered text would lose them and this fails.
        """
        parameters = ExampleBundle._simulationParameters()
        self.assertIsNotNone(
            parameters, "the generator constants must be importable in a checkout")
        self.assertIn("%s log2 units" % parameters["effectSize"], self.document)
        self.assertIn("%.0f%%" % (parameters["signalFraction"] * 100), self.document)
        self.assertIn("%.0f%%" % (parameters["diffuseRate"] * 100), self.document)
        self.assertIn(str(parameters["noise"]), self.document)
        # The literal '%%' bug: a printf escape with no format operator ships
        # "57%%" to the reader.
        self.assertNotIn("%%", self.document)

    def test_the_document_names_the_seed_that_reproduces_the_data(self):
        manifest = ExampleDatasets.loadManifest(REAL_EXAMPLE_FILES)
        self.assertIn(str(manifest.get("seed")), self.document)

    def test_one_scenario_can_be_downloaded_alone(self):
        directory = tempfile.mkdtemp(prefix="paintomics-bundle-one-")
        try:
            wanted = self.scenarios[0]["id"]
            archive = buildInto(directory, scenarioId=wanted)
            try:
                names = set(archive.namelist())
            finally:
                archive.close()
            for relative in ExampleDatasets.declaredFiles(self.scenarios[0]):
                if os.path.isfile(ExampleDatasets.absolutePath(
                        REAL_EXAMPLE_FILES, relative)):
                    self.assertIn(PREFIX + relative, names)
            self.assertLess(len(names), len(self.names),
                            "one scenario should be smaller than all of them")
        finally:
            shutil.rmtree(directory, ignore_errors=True)

    def test_an_unknown_scenario_is_refused_by_name(self):
        with self.assertRaises(ExampleDatasets.UnknownScenario):
            ExampleBundle.scenariosFor(REAL_EXAMPLE_FILES, "no-such-dataset")

    def test_a_pipeline_gets_exactly_its_own_datasets(self):
        """Each converter page's button ships what that page can load."""
        for pipeline in ("mirna2genes", "more"):
            selected = ExampleBundle.scenariosFor(REAL_EXAMPLE_FILES,
                                                  pipeline=pipeline)
            self.assertTrue(selected, "no datasets for %s" % pipeline)
            for scenario in selected:
                self.assertEqual(pipeline, scenario.get("pipeline"))

    def test_an_unknown_pipeline_is_refused_rather_than_sent_empty(self):
        """An empty archive reads as "this server has no examples"."""
        with self.assertRaises(ExampleDatasets.UnknownScenario):
            ExampleBundle.scenariosFor(REAL_EXAMPLE_FILES, pipeline="no-such-tool")

    def test_the_download_is_named_for_what_is_in_it(self):
        self.assertEqual("paintomics_example_data.zip", ExampleBundle.downloadName())
        self.assertEqual("paintomics_example_data_region-based.zip",
                         ExampleBundle.downloadName("region-based"))
        self.assertEqual("paintomics_example_data_mirna2genes.zip",
                         ExampleBundle.downloadName(pipeline="mirna2genes"))

    def test_selections_do_not_evict_each_others_archives(self):
        """Four buttons share one cache directory; each must stay warm.

        `_discardStaleArchives` matches on the selector prefix for this reason.
        Matching on the stem alone made every build delete the other three
        selections, so each page rebuilt ~40 MB on every click.
        """
        everything = ExampleBundle.bundleFor(REAL_EXAMPLE_FILES)
        scoped = ExampleBundle.bundleFor(REAL_EXAMPLE_FILES, pipeline="mirna2genes")
        self.assertNotEqual(everything, scoped)
        self.assertTrue(os.path.isfile(everything),
                        "building a pipeline bundle deleted the complete one")
        self.assertTrue(os.path.isfile(scoped))


class BundleEdgeCaseTest(unittest.TestCase):
    """Synthetic trees, for the cases the real one does not exhibit."""

    def setUp(self):
        ExampleDatasets.clearCache()
        self.root = tempfile.mkdtemp(prefix="paintomics-bundle-edge-")
        self.directory = tempfile.mkdtemp(prefix="paintomics-bundle-out-")

    def tearDown(self):
        shutil.rmtree(self.root, ignore_errors=True)
        shutil.rmtree(self.directory, ignore_errors=True)
        ExampleDatasets.clearCache()

    def writeScenario(self, scenarioId, folder, payload="a\tb\n1\t2\n"):
        dataDir = os.path.join(self.root, "datasets", folder, "data")
        os.makedirs(dataDir, exist_ok=True)
        path = os.path.join(dataDir, "values.tab")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(payload)
        with open(os.path.join(self.root, "datasets", folder, "README.md"),
                  "w", encoding="utf-8") as handle:
            handle.write("# %s\n" % scenarioId)
        return {
            "id": scenarioId, "title": scenarioId, "summary": "",
            "pipeline": "pathway-acquisition", "organism": "mmu",
            "databases": ["KEGG"], "simulated": True,
            "omics": [{"omicName": "Gene expression", "omicType": "gene",
                       "dataFile": "datasets/%s/data/values.tab" % folder}],
            "references": [],
        }, path

    def writeManifest(self, scenarios):
        os.makedirs(os.path.join(self.root, "datasets"), exist_ok=True)
        with open(os.path.join(self.root, ExampleDatasets.MANIFEST_NAME),
                  "w", encoding="utf-8") as handle:
            json.dump({"version": ExampleDatasets.SUPPORTED_VERSION,
                       "defaultScenario": scenarios[0]["id"],
                       "seed": 4242,
                       "generator": "src/AdminTools/scripts/exampledata",
                       "scenarios": scenarios}, handle)

    def test_an_oversized_member_is_skipped_and_named(self):
        """Silently dropping a declared file teaches the wrong dataset."""
        scenario, path = self.writeScenario("big", "01-big")
        self.writeManifest([scenario])

        original = ExampleBundle.MAX_MEMBER_BYTES
        ExampleBundle.MAX_MEMBER_BYTES = 1          # smaller than any real file
        try:
            archive = buildInto(self.directory, exampleFilesDir=self.root)
            try:
                names = set(archive.namelist())
                document = archive.read(DOCUMENT).decode("utf-8")
            finally:
                archive.close()
        finally:
            ExampleBundle.MAX_MEMBER_BYTES = original

        self.assertNotIn(PREFIX + "datasets/01-big/data/values.tab", names)
        self.assertIn("Not included", document)
        self.assertIn("datasets/01-big/data/values.tab", document)

    def test_a_missing_declared_file_is_reported_not_crashed(self):
        scenario, path = self.writeScenario("gone", "01-gone")
        self.writeManifest([scenario])
        os.remove(path)

        members, skipped = ExampleBundle.collectMembers(self.root, [scenario])
        self.assertEqual([], [m[0] for m in members
                              if m[0].endswith("values.tab")])
        self.assertIn("datasets/01-gone/data/values.tab",
                      [entry[0] for entry in skipped])

    def test_a_file_two_scenarios_share_is_collected_once(self):
        first, path = self.writeScenario("first", "01-first")
        second = dict(first, id="second")
        second["omics"] = [dict(first["omics"][0])]     # same dataFile
        self.writeManifest([first, second])

        members, _ = ExampleBundle.collectMembers(self.root, [first, second])
        paths = [relative for relative, _, _ in members]
        self.assertEqual(len(paths), len(set(paths)))

    def test_the_cache_key_moves_when_the_data_does(self):
        """A regenerated dataset must not keep serving yesterday's archive."""
        scenario, path = self.writeScenario("cached", "01-cached")
        self.writeManifest([scenario])

        first = ExampleBundle.bundleFor(self.root)
        self.assertTrue(os.path.isfile(first))

        with open(path, "a", encoding="utf-8") as handle:
            handle.write("3\t4\n")
        ExampleDatasets.clearCache()

        second = ExampleBundle.bundleFor(self.root)
        self.assertNotEqual(first, second,
                            "the archive was rebuilt to the same cache path")
        self.assertTrue(os.path.isfile(second))

    def test_a_partial_build_never_lands_at_the_destination(self):
        """A truncated zip is one a browser saves and a user cannot open."""
        scenario, _ = self.writeScenario("atomic", "01-atomic")
        self.writeManifest([scenario])
        destination = os.path.join(self.directory, "atomic.zip")

        broken = list(ExampleBundle.collectMembers(self.root, [scenario])[0])
        broken.append(("datasets/01-atomic/data/absent.tab",
                       os.path.join(self.root, "absent.tab"), 10))
        original = ExampleBundle.collectMembers
        ExampleBundle.collectMembers = lambda *a, **k: (broken, [])
        try:
            with self.assertRaises(OSError):
                ExampleBundle.buildBundle(self.root, destination)
        finally:
            ExampleBundle.collectMembers = original

        self.assertFalse(os.path.exists(destination),
                         "a failed build left an archive behind")
        leftovers = [name for name in os.listdir(self.directory)
                     if name.endswith(".part")]
        self.assertEqual([], leftovers, "a failed build left a temporary file")


if __name__ == "__main__":
    unittest.main(verbosity=2)
